### ISSUE TITLE
Q about future development

### ISSUE THREAD

**Issue by CharlotteAnne** [LieberInstitute/recount-brain#10]
Hi!

This is a heroic effort and resource - are there any plans to expand the number of projects re-annotated in line with the recount3 resource?

Thanks for all your work,

Charlotte

**Comment by lcolladotor** [comment]
Hi @CharlotteAnne,

We currently do not have funding support to keep expanding this project. Though I agree with you that it would be interesting to do so.

We do want to at least port the release of recount-brain to `recount3` (it can be done as a "collection" cc @Nick-Eagles). But we haven't prioritized this work.

Best,
Leo
