### ISSUE TITLE
Check into querying by ontology term for disease, location, etc. 

### ISSUE THREAD

**Issue by seandavi** [LieberInstitute/recount-brain#6]
Thanks for pulling in the ontology stuff. If someone on the team has time, it would be interesting allow queries of the type "location" = "supratentorial" (or whatever the correct ontology term is for that) and find all child terms that match. This would involved loading the full ontologies as DAGs and then querying for terms and all "more specific" children.

**Comment by lcolladotor** [comment]
Hi Sean,

See https://jhubiostatistics.shinyapps.io/recount-brain/ (also displayed via an iframe at http://lieberinstitute.github.io/recount-brain/)

At https://github.com/LieberInstitute/recount-brain/commit/b88579ce83c0f0529281677430181f6b0374a344 (and some other commits) I edited the `shinycsv` code from https://github.com/LieberInstitute/shinycsv to display `recount_brain_v2.csv`. Together with the extra ontology columns from https://github.com/LieberInstitute/recount-brain/commit/7f65f98f35430f2d7b4e7fbae482b06d0d02453f it's possible now to do the type of search you suggested. The plotting part of `shinycsv` could be improved, but well, that's another project. 

In any case, I think this shiny app will be good for users who are interested in exploring `recount_brain`.

Best,
Leo
